name = "spectracker-api"
main = "./apps/server/src/index.ts"
compatibility_date = "2026-02-20"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "specdev"
database_id = "522f179c-df17-400e-91fe-6c29191a97b4"